# backend/docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: amora_hub_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=amoradb_user
      - POSTGRES_PASSWORD=amoradb_password
      - POSTGRES_DB=amoradb
    ports:
      - "5432:5432"